In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

#Data Loading
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

#Cleanup Data /converting it into datetime format
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\Pradi\anaconda3\envs\python_subject\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
'[WinError 10054] An existing connection was forcibly closed by the remote host' thrown while requesting HEAD https://huggingface.co/datasets/lukebarousse/data_jobs/resolve/ed776e5a0a8c40ea9d5efbd800772ae52e140f3e/data_jobs.py
Retrying in 1s [Retry 1/5].
Using the latest cached version of the dataset since lukebarousse/data_jobs couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'default' at C:\Users\Pradi\.cache\huggingface\datasets\lukebarousse___data_jobs\default\0.0.0\ed776e5a0a8c40ea9d5efbd800772ae52e140f3e (last modified on Sat Jun 13 17:04:48 2026).

In [2]:
df.loc[:, 'salary_rate':'salary_hour_avg'].dropna(subset="salary_rate")

       salary_rate  salary_year_avg  salary_hour_avg
28            year         109500.0              NaN
43            hour              NaN             97.5
51            hour              NaN             72.5
77            year         140000.0              NaN
92            year         120000.0              NaN
...            ...              ...              ...
785624        year         139216.0              NaN
785641        year         150000.0              NaN
785648        year         221875.0              NaN
785682        year         157500.0              NaN
785692        year         157500.0              NaN

[33067 rows x 3 columns]

Retrieve the columns starting with job_title all the way to job_posted_date for rows with an index of 5 to 9. Use the loc method.

In [32]:
df.loc[5:9,'job_title':'job_posted_date']

,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date
5,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59
6,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18
7,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49
8,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34
9,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57

In [34]:
df.loc[5:9,'job_title':'job_posted_date']

,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date
5,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59
6,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18
7,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49
8,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34
9,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57

Select and display the job_title, job_location, and job_posted_date columns for rows where the job_posted_date is after '2023-05-01' using the loc method.

In [48]:
df.loc[df['job_posted_date']>'2023-05-01',['job_title','job_location','job_posted_date']]

,job_title,job_location,job_posted_date
0,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",2023-06-16 13:44:15
2,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",2023-10-10 13:14:55
3,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",2023-07-04 13:01:41
4,Data Engineer- Sr Jobs,"Washington, DC",2023-08-07 14:29:36
5,GCP Data Engineer,Anywhere,2023-11-07 14:01:59
...,...,...,...
785694,Data Engineer,"Graz, Austria",2023-05-07 07:07:37
785696,Senior Analytics Engineer,"Colombia, Huila, Colombia",2023-10-23 06:31:25
785698,"Data Engineer, Gerencia Business Intelligence","Las Condes, Chile",2023-08-09 06:32:00
785701,"Data Engineer, Gerencia Business Intelligence","Santiago, Chile",2023-08-09 06:31:57
785706,Junior Data Engineer,"Lima, Peru",2023-11-08 06:34:48